Part 1 - Question 1

In [3]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 12.2 MB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

A = np.array([1, 3, 5, 7, 9])
B = np.array([3, 5, 6, 7, 8])

vertical_stack = np.vstack((A, B))
print("Vertical Stack:\n", vertical_stack)

horizontal_stack = np.hstack((A, B))
print("\nHorizontal Stack:\n", horizontal_stack)

Vertical Stack:
 [[1 3 5 7 9]
 [3 5 6 7 8]]

Horizontal Stack:
 [1 3 5 7 9 3 5 6 7 8]


Question 2

In [5]:
common_elements = np.intersect1d(A, B)
print("\nCommon Elements between A and B:", common_elements)


Common Elements between A and B: [3 5 7]


Question 3 

In [6]:
range_mask = (A > 5) & (A < 10)
A_in_range = A[range_mask]
print("\nNumbers in A between 5 and 10:", A_in_range)


Numbers in A between 5 and 10: [7 9]


Question 4 

In [7]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

mask = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
filtered_iris = iris_2d[mask]
print("\nFiltered iris_2d rows where petallength > 1.5 and sepallength < 5.0:\n", filtered_iris)


Filtered iris_2d rows where petallength > 1.5 and sepallength < 5.0:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]
